#!/usr/bin/env bash

SETUP_GIT_DIR=`dirname $(readlink -f $0)`
SETUP_EXT_DIR=$SETUP_GIT_DIR/external
SETUP_BIN_DIR=$SETUP_GIT_DIR/bin
FORCE_SETUP=0

echo "SETUP_GIT_DIR: $SETUP_GIT_DIR"

mkdir -p ~/toolwares/
mkdir -p ~/.config/

is_zsh() {                                                                    
    [[ "$SHELL" =~ zsh ]] && return 0 || return 1                             
}                                                                             
is_bash() {                                                                   
    [[ "$SHELL" =~ bash ]] && return 0 || return 1                            
}                                                                             
                                                                              
_addlineto() { # add $2 to file $1, if $2 isn't in $1                         
    if [ ! -f $1 ];then                                                       
        echo "$1 doesn't exist, skip"; return 0                               
    fi                                                                        
    matchline=$(grep -F "$2" $1)                                              
    if [ $? -eq 0 ];then                                                      
        echo $matchline is already in: $1                                     
    else                                                                      
        echo "" >> $1 # add a blank line, incase rc file has no \n at file end
        echo $2 >> $1                                                         
    fi                                                                        
}                                                                             

_addlinetorc() {
  [[ -f ~/.bashrc ]] && _addlineto ~/.bashrc "$@"
  [[ -f ~/.zshrc ]] && _addlineto ~/.zshrc "$@"
}
# 把这个仓的 bin 目录加到PATH
_addlinetorc "export PATH=$SETUP_GIT_DIR/bin:\$PATH"
_addlinetorc "alias ta='tmux attach'"
_addlinetorc "alias tn='tmux new -s '"
  [[ -f ~/.bashrc ]] && _addlineto ~/.bashrc "alias rcreload='source ~/.bashrc'"
  [[ -f ~/.zshrc ]] && _addlineto ~/.zshrc "alias rcreload='source ~/.zshrc'"


setup_for_tmux_conf() {
  TMUX_DIR="$SETUP_EXT_DIR/oh-my-tmux"
  [[ ! -d $TMUX_DIR ]] && git clone --single-branch https://github.com/gpakosz/.tmux.git $TMUX_DIR
  mkdir -p ~/.config/tmux
  ln -s -f $TMUX_DIR/.tmux.conf ~/.config/tmux/tmux.conf
  ln -s -f $SETUP_GIT_DIR/.tmux.conf.local ~/.config/tmux/tmux.conf.local
}

setup_for_tmux_bin() {
  TMUX_BIN_DIR="$SETUP_EXT_DIR/tmux"
  [[ ! -d $TMUX_BIN_DIR ]] && git clone https://github.com/tmux/tmux.git $TMUX_BIN_DIR
  cd $TMUX_BIN_DIR
  if [[ ! -f $TMUX_BIN_DIR/tmux ]]; then
    sh autogen.sh
    sudo apt-get install libevent-dev
    ./configure && make
  fi
  [[ -f $TMUX_BIN_DIR/tmux && ! -f $TMUX_BIN_DIR/tmux ]] && cp $TMUX_BIN_DIR/tmux $SETUP_BIN_DIR
}

setup_for_fzf() {
  FZFBIN="fzf-0.74.4-linux_amd64.tar.gz"
  cd $SETUP_EXT_DIR
  [[ ! -f $SETUP_EXT_DIR/$FZFBIN ]] && wget https://github.com/junegunn/fzf/releases/download/v0.74.4/fzf-0.74.4-linux_amd64.tar.gz --no-check-certificate
  [[ ! -f fzf ]] && xzf $FZFBIN
  [[ -f fzf && ! -f $SETUP_BIN_DIR/fzf ]] && cp fzf $SETUP_BIN_DIR
  _addlinetorc 'eval "$(fzf --bash)"'
}

setup_for_nvim() {
  NVIMDIR="~/nvimrc"

  [[ ! -d $NVIMDIR ]] && git clone https://github.com/serenemoon/nvimrc.git $NVIMDIR
  NVIMLINK=~/.config/nvim
  [[ -L $NVIMLINK ]] && rm $NVIMLINK 
  [[ -d $NVIMLINK && ! -L $NVIMLINK ]] && mv $NVIMLINK ~/.config/nvim.bak.$$
  ln -f -s $NVIMDIR $NVIMLINK && echo ~/.config/nvim linked to $DIRN
}

setup_for_git() {
  git config --global http.sslverify false                
  git config --global https.sslverify false               
  git config --global alias.st status                     
  git config --global alias.co checkout                   
  git config --global alias.cp cherry-pick                
  git config --global alias.cm commit                     
  git config --global alias.cme "commit --amend --no-edit"
  git config --global alias.cma "commit --amend"          
  git config --global alias.rsh "reset --hard HEAD"       
  git config --global alias.dfh "diff HEAD"               
  git config --global alias.dfhs "diff HEAD --stat"       
  git config --global alias.df  "diff HEAD~1"             
  git config --global alias.dfs  "diff HEAD~1 --stat"     
  git config --global alias.logs  "log --stat"            
  git config --global alias.logf  "log --format=fuller"   
  git config --global alias.rl  "reflog"                  
  git config --global alias.rlf  "reflog --pretty=fuller" 
  git config --global alias.br  "branch"                  
  git config --global alias.cl  "clean -f -d"             
  git config --global alias.rsh  "reset --hard HEAD"      
  git config --global alias.rsh1  "reset --hard HEAD~"    
  git config --global core.excludesfile "~/.gitignore"    
  git config --global --add oh-my-zsh.hide-status 1       
  git config --global --add oh-my-zsh.hide-dirty 1
}

# -- CLI flags: each setup_for_xxx has a default, override via args -------------
#   ./setup                  -> run all enabled-by-default steps
#   ./setup --no-tmux-conf   -> skip tmux conf
#   ./setup --tmux-bin       -> force enable tmux bin (disabled by default)
#   ./setup --list           -> show step status and exit
ENABLE_TMUX_CONF=1
ENABLE_TMUX_BIN=0
ENABLE_FZF=0
ENABLE_GIT=1
ENABLE_NVIM=0

usage() {
  cat <<EOF
Usage: $0 [options]
  --tmux-conf          enable  setup_for_tmux_conf
  --no-tmux-conf       disable setup_for_tmux_conf
  --tmux-bin           enable  setup_for_tmux_bin
  --no-tmux-bin        disable setup_for_tmux_bin
  --fzf                enable  setup_for_fzf
  --no-fzf             disable setup_for_fzf
  --git                enable  setup_for_git
  --no-git             disable setup_for_git
  --nvim               enable  setup_for_nvim
  --no-nvim            disable setup_for_nvim
  --all                enable all steps
  --list               show step status and exit
  -h, --help           show this help
EOF
}

LIST_ONLY=0
while [[ $# -gt 0 ]]; do
  case "$1" in
    --tmux-conf)    ENABLE_TMUX_CONF=1 ;;
    --no-tmux-conf) ENABLE_TMUX_CONF=0 ;;
    --tmux-bin)     ENABLE_TMUX_BIN=1 ;;
    --no-tmux-bin)  ENABLE_TMUX_BIN=0 ;;
    --fzf)          ENABLE_FZF=1 ;;
    --no-fzf)       ENABLE_FZF=0 ;;
    --git)          ENABLE_GIT=1 ;;
    --no-git)       ENABLE_GIT=0 ;;
    --nvim)         ENABLE_NVIM=1 ;;
    --no-nvim)      ENABLE_NVIM=0 ;;
    --all)          ENABLE_TMUX_CONF=1; ENABLE_TMUX_BIN=1; ENABLE_FZF=1; ENABLE_GIT=1; ENABLE_NVIM=1 ;;
    --list)         LIST_ONLY=1 ;;
    -h|--help)      usage; exit 0 ;;
    *) echo "unknown option: $1"; usage; exit 1 ;;
  esac
  shift
done

echo "step status:"
echo "  tmux_conf : $ENABLE_TMUX_CONF"
echo "  tmux_bin  : $ENABLE_TMUX_BIN"
echo "  fzf       : $ENABLE_FZF"
echo "  git       : $ENABLE_GIT"
echo "  nvim      : $ENABLE_NVIM"

if [[ $LIST_ONLY -eq 1 ]]; then exit 0; fi

[[ $ENABLE_TMUX_CONF -eq 1 ]] && setup_for_tmux_conf
[[ $ENABLE_TMUX_BIN  -eq 1 ]] && setup_for_tmux_bin
[[ $ENABLE_FZF       -eq 1 ]] && setup_for_fzf
[[ $ENABLE_GIT       -eq 1 ]] && setup_for_git
[[ $ENABLE_NVIM      -eq 1 ]] && setup_for_nvim
